<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerXcwwkgn\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerXcwwkgn/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerXcwwkgn.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerXcwwkgn\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerXcwwkgn\appDevDebugProjectContainer(array(
    'container.build_hash' => 'Xcwwkgn',
    'container.build_id' => '81113c5f',
    'container.build_time' => 1517935680,
));
